image: debian:testing

stages:
  - build

.tags: &tags
  tags:
    - general

before_script:
  - apt-get -y update
  - apt-get -y install nim

build_bin:
    tags:
        - general
    stage: build
    script:
        - nimble build
    artifacts:
      paths:
        - phishstats_client

